### ISSUE TITLE
State grid map default legend shows all values in one color

### ISSUE THREAD

**Issue by shmcminn** [nprapps/dailygraphics-next#12]
screenshot attd
<img width="758" alt="Screen Shot 2019-04-17 at 10 41 46 AM" src="https://user-images.githubusercontent.com/11263479/56296971-76f0dd80-60fd-11e9-981b-33f82961585f.png">

**Comment by thomaswilburn** [comment]
This is an issue with the default template sheet for this interactive--we split on `|` instead of `,` since the new rig auto-casts values from Sheets, but the sheet itself still has comma-separated values. When we're fully onboard with Next (which I think is generally true) we should change this, in addition to updating/replacing the default chatter (which currently still contains Jinja code for the old rig).

**Comment by thomaswilburn** [comment]
Closing this as I've finally updated the template sheets to match Next by default.
