### ISSUE TITLE
`sync` hangs when retrieving remote file lists where the folder contains a lot of files

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-next#58]
Running into an issue with `sync` with a project with thousands of files in a folder (the [hospital capacity tracker](https://www.npr.org/sections/health-shots/2020/12/09/944379919/new-data-reveal-which-hospitals-are-dangerously-full-is-yours), where the `synced/` folder contains a folder (`fips_files/`) with ~2.5k json files — one for each county in the dataset). @connjin has had this issue intermittently for a while; it's just started with consistency for @DanielJWood and I.

**What happens:** I'll run `node cli sync __SLUG__`, and the operation seems to hang where we're retrieving the file list from the remote server:

https://github.com/nprapps/dailygraphics-next/blob/master/lib/syncAssets.js#L43

**What I've tried:**

* It doesn't seem to make a difference if I'm connected to VPN.
* It doesn't seem to make a difference if I use the `--push` flag.
* If I empty out the remote `synced/` folder for this graphic via the AWS console, syncing then works just fine.
* If I delete a particularly large (200MB) datafile from the remote `synced/` folder, syncing still hangs. (This suggests that the issue may be with number of files, not size of individual files?)
* If I delete just the `fips_files/` folder from the remote `synced/` folder, syncing then works just fine.

Not sure if this is related to our [recent update to the AWS SDK](https://github.com/nprapps/dailygraphics-next/pull/54). @thomaswilburn you [mentioned](https://github.com/nprapps/dailygraphics-next/issues/52#issuecomment-1138933323) that this uses `ListObjectsV2`? Just noticed this in the [API reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html):

> Returns some or all (up to 1,000) of the objects in a bucket with each request.

**Comment by thomaswilburn** [comment]
This has always been the way the API works, not just with the v2 function call. And the `ls()` function does accumulate past 1,000 results using the marker from the API, which is why you're not getting this failure every time (https://github.com/nprapps/dailygraphics-next/blob/master/lib/s3.js#L75). 

My suspicion is that something is causing a connection lag, and we're not setting a timeout (which for the service defaults to two minutes), so it'll happily sit and do nothing if one item in a batch fails to connect promptly. We may need to add some additional logging to the progress of the download stream (probably in this function: https://github.com/nprapps/dailygraphics-next/blob/master/lib/s3.js#L43) to see exactly what's happening here. Alternately, when the S3 client is created, we could set a much shorter timeout to see if this errors instead of just hanging.

**Comment by alykat** [comment]
Ah interesting!

If I add a `console.log(marker)` to that `ls` function:

```var ls = async function (bucket, path) {
  var response = null;
  var list = [];
  do {
    var marker = response && response.next;
    console.log(marker);
    response = await getRemote(bucket, path, marker);
    list.push(...response.items);
  } while (response.next);
  return list;
};
```

I get `null` the first time, and then the same thing ad infinitum, like the marker for the next batch isn't updating?

```
null
dailygraphics/graphics/covid-hosp-county-graphic-20201207/synced/fips_files/26053.json
dailygraphics/graphics/covid-hosp-county-graphic-20201207/synced/fips_files/26053.json
dailygraphics/graphics/covid-hosp-county-graphic-20201207/synced/fips_files/26053.json
```

**Comment by thomaswilburn** [comment]
Ah, interesting! It does look like the API switched to using `response.NextContinuationToken` in V2 (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property), and it's possible that they kept `response.next` for backwards compatibility but aren't currently returning the correct value there (if it's on an old API version, I can easily imagine that they'd occasionally break it and not notice). I can take a look at this tomorrow and probably fix it in short order.

**Comment by thomaswilburn** [comment]
I've update the S3 wrapper here: https://github.com/Chalkbeat/dailygraphics-next/commit/be1c4c543ffc33f378d6f0cffd52f294abd9f55d It now uses the V2's ContinuationToken instead of passing the last downloaded item to the Marker parameter. In theory, this isn't really much different, but hopefully in practice Amazon is paying better attention to that particular API detail.

If the problem is that it hangs while listing files, this will hopefully fix that. If, however, the problem is actually in the download/upload process, it's not going to make a difference there. Feel free to keep me posted!
